import { BlogPost } from './types';

export const MOCK_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Racing: ¿otro cabaret?",
    excerpt: "Ni Mostaza Merlo ni Juan José Pizzuti ni el Cholo Simeone ni Rubén Paz: en la mente de los hinchas de Racing, la salvación depende de...",
    author: "Walter F.",
    date: "14 Oct 2024",
    commentsCount: 34,
    category: "Fútbol Argentino",
    imageUrl: "https://picsum.photos/id/1058/800/600",
  },
  {
    id: 2,
    title: "Ventana europea: Crisis financiera y fútbol",
    excerpt: "El cuanto choque de la burbuja financiera globalizada contra el respetable mundo del fútbol parece inminente. ¿Cómo afectará a los clubes ingleses?",
    author: "Admin",
    date: "12 Oct 2024",
    commentsCount: 12,
    category: "Internacional",
    imageUrl: "https://picsum.photos/id/1015/800/600",
    hasVideo: true,
  },
  {
    id: 3,
    title: "Selección Argentina: DT se busca",
    excerpt: "Hablar hoy del entrenador de la selección argentina es, de alguna manera, debatir sobre el futuro del fútbol nacional. Nombres sobran, ideas faltan.",
    author: "Martin C.",
    date: "10 Oct 2024",
    commentsCount: 128,
    category: "Selección",
    imageUrl: "https://picsum.photos/id/1025/800/600",
  },
  {
    id: 4,
    title: "Chacarita entra a la cancha",
    excerpt: "Así entra Chacarita, que viste una de las camisetas más pintorescas y tradicionales de nuestro fútbol. El proyecto del nuevo estadio avanza.",
    author: "Redacción",
    date: "08 Oct 2024",
    commentsCount: 5,
    category: "Ascenso",
    imageUrl: "https://picsum.photos/id/147/800/600",
  },
  {
    id: 5,
    title: "Estudiantes campeón del mundo: 40 años",
    excerpt: "40 años. Nada. Se dice rápido. Bilardo, Verón y la mística pincha que conquistó Old Trafford en una noche inolvidable.",
    author: "Historiador",
    date: "05 Oct 2024",
    commentsCount: 89,
    category: "Historia",
    imageUrl: "https://picsum.photos/id/452/800/600",
  },
   {
    id: 6,
    title: "San Lorenzo sigue...",
    excerpt: "El equipo de Boedo no se detiene y sigue sumando puntos clave en la lucha por el campeonato local.",
    author: "Cuervo10",
    date: "03 Oct 2024",
    commentsCount: 42,
    category: "Primera División",
    imageUrl: "https://picsum.photos/id/1040/800/600",
  }
];